### ISSUE TITLE
save($entity) throws PDOexception on existing primary key

### ISSUE THREAD

**Issue by batiste93** [spotorm/spot2#111]
save() does not update when primary key exists 
It seems to be trying to insert instead of updating

```
$itemMapper = $this->spot->mapper('Entity\Item');
$itemEntity = $itemMapper->build($itemData);
$itemMapper->save($itemEntity);
```

throws 
`Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '00070892210139' for key 'PRIMARY'`

and I have the PK defined as such
`'ID'          => ['type' => 'string', 'primary' => true, 'length'=> 15]`

**Comment by Artamiel** [comment]
That's because `_isNew` property in `Spot\Entity` is never set to `false`. On the other hand, there is a built-in method for this, called `upsert()` which first tries to insert the entity, and if unique constraint error is triggered, it automatically tries to update the entity.

**Comment by vlucas** [comment]
> That's because `_isNew` property in `Spot\Entity` is never set to `false`.

If this is true, this definitely seems like a bug.

**Comment by Artamiel** [comment]
Well, that depends. As far as I can see, `->isNew()` is called only when `Collection` is being created. It would be better when specific record is queried, for the entity to be marked as old with `isNew()`. This way when `save()` is will work as expected.

**Comment by MarcusFulbright** [comment]
I'm new to Spot and just ran into this problem as well. Before this gets fixed, how should one go about persisting updated changes to entities?

**Comment by jsangrador** [comment]
Hi all, in the same line as @MarcusFulbright I am also having trouble persisting updates (to Postgres, if that matters). $mapper->update($entity) doesn't complain, returns the value 1, and the DB data is not updated. Maybe I am missing something? Thanks!

**Comment by tuupola** [comment]
@jsangrador what were you doing before?

**Comment by tuupola** [comment]
@batiste93 I think that this is logical and how I would expect it to work. If you create a **new** entity which has primary key which already exists in database and you call `save()` you are supposed to get unique constraint error. That is because the primary key used by the new entity already exists.

When you load an **existing** entity from database, update the entity data and then call `save()` on it will result on updating the data.

**Comment by jsangrador** [comment]
I will use my own shame to try help others. What I was doing before was to guess how the whole update cycle was supposed to work _without reading the docs_. When I did, I understood better. Anyway, some lines for the complete novice in the CRUD section would be nice.

**Comment by tuupola** [comment]
This seemed to be user error.
