### ISSUE TITLE
I don't understand basics 

### ISSUE THREAD

**Issue by gabrieldarezzo** [spotorm/spot2#150]
I really confused.

Already try everthing i know and fails.

But I just try simple example to run hello word like.
Where i put class?

Example I have my simple table:

`CREATE table user(
     id             int(8) PRIMARY KEY AUTO_INCREMENT
    ,name           VARCHAR(50) NOT NULL
)ENGINE=InnoDB;

INSERT INTO user (nome) values ('Test 1');
INSERT INTO user (nome) values ('Test 2');`

Can anyone show-me how i can saw array working?

**Comment by gabrieldarezzo** [comment]
My
index.php:
`<?php

require_once 'vendor/autoload.php';

$cfg = new \Spot\Config();

// MySQL
$cfg->addConnection('mysql', 'mysql://root:@localhost/dividiae');

$spot = new \Spot\Locator($cfg);



class Noticia extends Spot\Mapper{
    public function mostRecentPostsForSidebar(){
       return $this->where(['id' => 1]);
    }
}

$postMapper = $spot->mapper('Noticia');
`

**Comment by FlipEverything** [comment]
You are doing it wrong. Please read the [documentation](http://phpdatamapper.com/) carefully.

You can start by creating a file called User.php with the following content:
```php
<?php
namespace Entity;
class User extends \Spot\Entity
{
    protected static $table = 'users';
    public static function fields()
    {
        return [
            'id'           => ['type' => 'integer', 'primary' => true, 'autoincrement' => true],
            'name'        => ['type' => 'string', 'required' => true]
        ];
    }
}
```
**Please note that** Entity classes can be named and namespaced however you want to set them up within your project structure. For the following examples, the Entities will just be prefixed with an Entity namespace for easy psr-0 compliant autoloading. 

You can learn about namespaces from online tutorials [like this](https://jtreminio.com/2012/10/composer-namespaces-in-5-minutes/).

That will be your first entity. Now you have to create the users table with a script like this:
```php
$cfg = new \Spot\Config();
$cfg->addConnection('mysql', 'mysql://root:@localhost/dividiae');
$spot = new \Spot\Locator($cfg);

$mapper = $spot->mapper('Entity\User');
$mapper->migrate();
```

After this you can execute [CRUD operations](http://phpdatamapper.com/docs/crud/).

Insert example:
```php
$cfg = new \Spot\Config();
$cfg->addConnection('mysql', 'mysql://root:@localhost/dividiae');
$spot = new \Spot\Locator($cfg);

$mapper = $spot->mapper('Entity\User');
$entity = $mapper->create([
    'name' => 'Test User'
]);
```

You can get all the users by calling something like this:
```php
$cfg = new \Spot\Config();
$cfg->addConnection('mysql', 'mysql://root:@localhost/dividiae');
$spot = new \Spot\Locator($cfg);

$mapper = $spot->mapper('Entity\User');
$users = $mapper->all();

foreach ($users as $user) {
 ...
 // example
 echo $user->name;
 ....
}
```

**Comment by Sysix** [comment]
> foreach ($users as $user) 

how does someone knows it? I searched 1 hour for it. Please add an Example to how to use a Mapper for output something

**Comment by marcelloh** [comment]
The part where the mapper plays a rol, is documented in the comment before your comment.

You can actually write your own functions in the mapper, like:
$users = mapper->getAllWithGender"M");

and then still do:
foreach ($users as $user) {
 echo $user->name;
}

I personnaly put everything in arrays (within the mapper functions),
and have it rendered in a twig-template (dynamically)

**Comment by FlipEverything** [comment]
@Sysix I think that functionality is expected or at least it was for me. If you're confused you can always look at one of the [tests](https://github.com/vlucas/spot2/blob/master/tests/CRUD.php). I learned a lot of things from them. 

Tip: For example if you `var_dump()` variables you can maybe figure out what they do.
