### ISSUE TITLE
example skripts

### ISSUE THREAD

**Issue by StephanKrauss** [spotorm/spot2#177]
Hello,

i'm a beginner in spot2.
Is there a way to get the sql dump and the entity and mapper skripts ?
Mapper skripts for post, author and comments.

Please help.

Your sincerly

Stephan

**Comment by marcelloh** [comment]
You can actually create the table of an entity yourself in an easy way:
```
$mapper->migrate(); 
```

The only thing is, when you have relations, it can go wrong unfortunately.
If it does, the quick way it to make comments out of the relation-part in a entity,
do a migrate, then uncomment, and do a migrate again.

**Comment by StephanKrauss** [comment]
When i use the Entity/posts for migrate, i get an exception. Doctrine DBAL say: unknown type 'int'.
When i use  $types = \Doctrine\DBAL\Types\Type::getTypesMap(); i missing type 'int'.

Your sincerly

Stephan

**Comment by marcelloh** [comment]
Can you show the entity?
My configuration shows something like this:
```
            'id'                        => ['type' => 'integer', 'primary' => true, 'autoincrement' => true],
```

**Comment by vlucas** [comment]
You have to use `integer` - not `int` :)
