### ISSUE TITLE
Add ability to chain relationed entities

### ISSUE THREAD

**Issue by pabloRei** [spotorm/spot2#18]
Basically, I have an entity (contact) with a 'hasOne' relationship with a second one: 'user' , and this 'user' entity has another 'hasOne' relationship with a third entity. 
I can get to the third one by doing this in the 'contact' entity:

```
$this->user->execute()->member->execute();
```

It would be great if I can just do something like:

(from the first entity)

```
$this->user->member;
```

Best,

**Comment by nebulousGirl** [comment]
Might be working from the changes in this pull request: https://github.com/vlucas/spot2/pull/135

**Comment by vlucas** [comment]
I'll have to write a test for this to verify.

**Comment by tuupola** [comment]
#135 has been merged.
