### ISSUE TITLE
Problem in composer requirements

### ISSUE THREAD

**Issue by bgillet** [spotorm/spot2#194]
Composer.json file is not correct.

Version for package "doctrine/dbal" is locked ("2.5.4"). It should be "^2.5".

Latest stable version of Doctrine DBAL is "2.5.5". If you use Composer from command line to add Spot2 package on an existing uptodate Symfony project, you cannot install it because you already have Doctrine DBAL "2.5.5" installed.

To bypass this, you must edit your composer.json file manually and add your "vlucas/spot2" requirement BEFORE "doctrine/orm". On next composer update, it will download an install Spot2 and also downgrade Doctrine DBAL to "2.5.4".

**Comment by tuupola** [comment]
Personally I agree. We should be able to trust DBAL does not break BC. However I remember @vlucas mentioning that there is a reason for this. Do I remember correctly?

**Comment by vlucas** [comment]
Yes - I agree that we should be able to trust the DBAL team to not break BC here. This can probably be safely changed.

**Comment by hakuno** [comment]
@vlucas @tuupola This thread may be closed since it's solved.
