### ISSUE TITLE
Running batch updates?

### ISSUE THREAD

**Issue by keevitaja** [spotorm/spot2#195]
How can i do 

`update sometable set something=1 where otherthing=2`

??

**Comment by tuupola** [comment]
Usually you work with entities so something like following untested code.

```php
$things = $mapper->where(["otherthing" => 2]);
foreach ($things as $thing) {
    $this->something = 1;
    $mapper->save($thing);
}
```

Or the following might also work. Not sure though.

```php
$mapper->query("UPDATE sometable SET something=1 WHERE otherthing=2");
```

http://phpdatamapper.com/docs/complex-queries/

**Comment by marcelloh** [comment]
This works for queries that don't fit yet:
```
$result = $mapper->exec($sql);
```
