### ISSUE TITLE
Problem updating entity with multiple primary key column

### ISSUE THREAD

**Issue by michalp82** [spotorm/spot2#197]
I have got problem with updating entity with multiple primary key column.

Table definition

```
public static function fields() {
        return [
            'storeNo' => ['type' => 'string','primary'=>true, 'required' => true],
            'weekday' => ['type' => 'integer','primary'=>true, 'required' => true],
            'open_hour' => ['type' => 'integer'],
            'close_hour' => ['type' => 'integer'],
        ];
    }
```

When i try to update an entity using mapper `update` method it update all rows in databases with the same weekdDay. Mapper create such SQL:`UPDATE `opening_hours` SET `open_hour` = ?, `close_hour` = ? WHERE `weekday` = ?`. A `storeNo` key is missing in where clause.

I know that, I can do update with raw sql, but i want to do this with orm funcionality :)

**Comment by tuupola** [comment]
Two primary keys seems a bit unorthodox. Have you considered using compound unique index instead?

```
'storeNo'    => ['type' => 'string', 'required' => true, 'unique' => 'storeNoWeekday']
'weekday' => ['type' => 'string', 'required' => true, 'unique' => 'storeNoWeekday']
```

**Comment by michalp82** [comment]
Spot required a primary key column.

`"Fatal error: Uncaught exception 'Spot\Exception' .... with message has no primary key field"`

Problem is in this code fragment:

`$result = $this->resolver()->update($this->table(), $data, [$this->primaryKeyField() => $this->primaryKey($entity)]);`

As you can see mapper always takes onlu 1 primary key column. So where has only 1 column not 2.

**Comment by tuupola** [comment]
Make one column primary key.

**Comment by vlucas** [comment]
@michalp82 Spot does not handle multiple primary keys. You need to make only one primary as @tuupola has shown. Like this:

```php
'storeNo'    => ['type' => 'string', 'required' => true, 'primary' => true, 'unique' => 'storeNoWeekday']
'weekday' => ['type' => 'string', 'required' => true, 'unique' => 'storeNoWeekday']
```

**Comment by michalp82** [comment]
The problem is in update query. 

My sql data
```
'1558', 1, 8, 20
'1558', 2, 8, 20
'1558', 3, 8, 20
'1558', 4, 8, 20
'1558', 5, 8, 20
'1558', 6, 8, 20
'1558', 7, 8, 20
````

When I use $mapper->update(entity), SQL update always update all the rows of storeNo 1558, becouse in where clause is one primary key storeNo: ``UPDATE `opening_hours` SET `open_hour` = ?, `close_hour` = ? WHERE `storeNo` = ?``
I dont want to use autoincrement id column in this situation

Now the only way to do update is raw sql.

**Comment by gregor-tb** [comment]
Also Spot requires a primary key that is numeric because there a some "is_numeric()" checks for Mapper::get(), Mapper::delete() and so on.

**Comment by Arzaroth** [comment]
I'll dig up this issue because I stumbled across the same issue earlier today.
I would say the issue is located in Mapper.php, line 849.

It is a broader issue (meaning, using multiple primary key instead of a autoincrement PK + compound unique index), but even if Spot does not support multiple PK as of now, I think Mapper::update should do the UPDATE requests against compound unique index as well as PK.

**Comment by tuupola** [comment]
> even if Spot does not support multiple PK as of now, I think Mapper::update should do the UPDATE requests against compound unique index as well as PK.

I fail to see the logic in this. Since the primary key is unique what is the reason to use the compound index too?

**Comment by nebulousGirl** [comment]
The storeNo is not unique and that is the problem. Why can't you add an autoincrement primary key even if it's just for Spot?

Spot requires a primary key and relies on it to make all operations. It was never intended to work in the way you are trying to.

**Comment by nebulousGirl** [comment]
After reviewing the code, I can see how it might be possible to alter the `update` method to be able to pass custom parameters to the where clause of the UPDATE query using a new option.

But it still is risky not to use a primary unique key because Spot relies on it not only on updates, but also for all relations.

**Comment by tuupola** [comment]
Personally I think that would be opening a can of worms. Easy and working solution is just to use numeric primary key as Spot requires. You cannot cater to everyone.
