### ISSUE TITLE
Call For New Maintainer/Owner of Spot ORM

### ISSUE THREAD

**Issue by vlucas** [spotorm/spot2#213]
## Spot ORM needs a new owner

Spot has a few issues and PRs piling up, and needs some love and attention.

I no longer write PHP full-time (these days I am slinging JavaScript on frontend, Node.js, and mobile apps), so I am not using Spot every day like I used to when I made it. This means that I am always a few steps removed from the pain points, and I don't want Spot the project to die due to my own lack of use.

So... who wants to assume ownership of Spot? I will transfer the repo, the packagist package, and the phpdatamapper.com website as well.

The only criteria are:

1. You are working in PHP with full time or near full time focus
2. You currently use Spot in a project (preferably your main one you work with daily)
3. You have contributed to Spot in some way (could just be reporting issues, fixing the docs, or facilitating discussion)

**Comment by vlucas** [comment]
Pinging @nebulousGirl @tuupola @willemwollebrants @marcojetson @FlipEverything @potfur @sebastian-galle @Savageman @marcelloh ... and others that I may have missed.

**Comment by FlipEverything** [comment]
Huh man, I bet that was a tough decision... I respect that you don't want the project to die. I value it very much because currently I rely on it heavily.

**Comment by vlucas** [comment]
Yes, it was a very tough decision. Spot is probably my favorite open source PHP project that I've made. I initially thought after getting a full time job using JavaScript 100% that I would still have time to properly maintain all my open source PHP projects, but that just has not been the case. I pretty much use JS for everything now. It's time for me to let go now so this project can have some new life.

**Comment by FlipEverything** [comment]
If nobody else applies I'll help you out gladly, but I don't want to jump in blindly because maintaining a fairly popular library is a big responsibility. I'm sure that there are a lot of people out there who are better qualified to do the job.
I just don't want this project to die.

**Comment by vlucas** [comment]
@FlipEverything I'll give it a few days since people may be on vacation and whatnot, but honestly I think you meet (and exceed) all the criteria already.

**Comment by marcojetson** [comment]
Hey, that's sad but I'm happy that you are having fun with new stuff :)
I don't have any experience maintaining a popular open source library but I would love to help so count me in!

**Comment by tuupola** [comment]
I have feeling  @nebulousGirl has the best knowledge on Spot internals and I'd like to see her take over.

That said Spot could however become a GitHub organisation. To take some pressure away from individual person pull request reviews could be setup. Any pull request should be approved by two or three members before merging.

Personally I have invested a lot in Spot by converting all our projects to use it. So yes, I use it every day in several projects. I am more than happy to help and be member of the organisation if it will be set up. 

I do not however currently feel confident with my knowledge of Spot internals.

**Comment by nebulousGirl** [comment]
I am pleased to be mentioned by @tuupola, but I cannot take over sole ownership of the project because I can't promise I will always be available to maintain the project in the coming months.

I would be open to joining a group of maintainers though and give some time to Spot whenever I can.

**Comment by leereichardt** [comment]
Hi,

Just wondering where this discussion got to? I'm starting to use this, but am nervous if it's not going to be actively maintained. I'd love to help out, but my skill level isn't really at a point where I feel I can do that.

**Comment by vlucas** [comment]
@leereichardt Spot is going to live on. There are several people here who have contributed to Spot already, and have a vested interest in continuing development and feature updates.

I think I am going to create a new "spotorm" GitHub org, move Spot there, and it will have multiple collaborators.

**Comment by tuupola** [comment]
@vlucas I have been pondering a long time whether I should become the new maintainer. It seems we think a like one of my plans was also to do the `spotorm` organisation. In any case are you in irc or Slack somewhere? I would like to have a chat.

**Comment by FlipEverything** [comment]
I think that creating the spotorm organisation is a great idea.

**Comment by FlipEverything** [comment]
In my opinion instead of moving the repository transfer it, othwerwise everything's gonna break. But I think you are aware of that. :)

**Comment by leereichardt** [comment]
@vlucas Thanks, that's good to hear!

**Comment by vlucas** [comment]
The move to @spotorm has been done. I also updated the package info on Packgist, so all the URLs should update properly and work now. There are already 5-6 collaborators that have accepted my invitations for this project.

**Comment by splio-aleroux** [comment]
Thanks for your work @vlucas. I only see this conversation now, despite my contribution to spotorm was small, i will be very happy to keep contributing to it.

**Comment by tuupola** [comment]
@vlucas I cannot label or assign etc. issues. Maybe a checkbox somewhere in the settings?

**Comment by vlucas** [comment]
@tuupola You should have full permissions now for the spot2 repo.

**Comment by vlucas** [comment]
Closing this issue since the @spotorm org has been created, and this project has been moved there. :)

**Comment by FlipEverything** [comment]
@vlucas Could you please approve me as a member of the team? :) I can't do anything with the project right now. Thank you!
