### ISSUE TITLE
 Spot\Mapper::save() must implement interface Spot\EntityInterface, array given,

### ISSUE THREAD

**Issue by tablecell** [spotorm/spot2#223]
```
$mapper=$spot->mapper('Entity\User');

$user=['usernmae'=>'tom','password'=>'xxxx'];
$mapper->save($user);
```
Catchable fatal error: Argument 1 passed to Spot\Mapper::save() must implement interface Spot\EntityInterface, array given,

**Comment by tuupola** [comment]
You must give `$mapper->save()` an `Entity\User` object, not an array.
