### ISSUE TITLE
Travis broken after moving to spotorm/spot2

### ISSUE THREAD

**Issue by tuupola** [spotorm/spot2#230]
It seems Travis still tries to fetch code from `vlucas/spot2`.

**Comment by tuupola** [comment]
@vlucas Ping. Can you update Travis or give me spotorm org access to Travis. It is currently waiting for approval from `spotorm` org owner which I assume is you.

<img width="753" alt="screenshot_280" src="https://cloud.githubusercontent.com/assets/21913/24990527/dd68c39a-203e-11e7-88f6-90901182ae44.png">

**Comment by vlucas** [comment]
Just updated the settings to connect it: https://travis-ci.org/spotorm/spot2

**Comment by tuupola** [comment]
Excellent. Thanks!
