### ISSUE TITLE
Customize SQL integrity constrains 

### ISSUE THREAD

**Issue by manelj** [spotorm/spot2#239]
How can i catch and customize spot orm SQL execution integrity violations or any other sql error?

**Comment by nebulousGirl** [comment]
With a try/catch or some kind of custom error handler, depends on what you want to achieve.

**Comment by FlipEverything** [comment]
+1, you can do something like this:

```php
// untested piece of code
$mapper = $spot->mapper('Entity');
try {
  $mapper->update($entity);
} catch (\Spot\Exception $spotException) {
  if (strpos($spotException->getMessage(), 'constraint violation') != false) {
    $response = new Forbidden;
  }
}
```

**Comment by FlipEverything** [comment]
Closing this issue, because of the inactivity. Feel free to reopen this if you have more questions regarding this subject.
