### ISSUE TITLE
Disable query caching

### ISSUE THREAD

**Issue by stojanovic-nikola** [spotorm/spot2#242]
Is it possible and how, to tell mapper not to cache query?

`$mapper->all(); // get data`
`$mapper->all(); // get fresh data again`

**Comment by tuupola** [comment]
Which cache do you mean? AFAIK Spot does not have a query cache.

**Comment by vlucas** [comment]
There is currently no caching:
https://github.com/spotorm/spot2/blob/master/lib/Query.php#L630

Maybe your query is already executed and you just have the resulting collection in your variable?
