### ISSUE TITLE
The search method is deprecated ? 

### ISSUE THREAD

**Issue by diego-sorribas** [spotorm/spot2#254]
Hello, I have an error when using the search method of Query class, it throw me this exception: 

Call to undefined method Spot\Entity\Manager::datasourceOptions()

Which is the best way to do a search?

Thanks!

**Comment by FlipEverything** [comment]
I'am not familiar with the search method. Maybe I'm blind but could not find anything useful in the commit history either. @vlucas could you please help us out?

**Comment by vlucas** [comment]
That's a bug. That should be a call to `tableOptions` instead.

Looks like there is a test Entity for searching, but no actual `search` performed in the tests or this would have been caught: https://github.com/spotorm/spot2/blob/e3c98c8fc212dc1ff83fabbea77048fb7691b12a/tests/Entity/Event/Search.php
