### ISSUE TITLE
CRUDelete (?

### ISSUE THREAD

**Issue by luchothoma** [spotorm/spot2#255]
I am new with Spot and in the doc http://phpdatamapper.com/docs/crud/ It does not say how to Delete an entity.... I try with ->delete( $primariKeyValue ) but it not works.

**Comment by luchothoma** [comment]
I solve it, it need the $ObjectToDelete, not the $id, althoug it will be useful update/add it to documentation.

**Comment by FlipEverything** [comment]
Unfortunately there are a lot of undocumented features in spot. I wanted to upgrade the documentation so many times in the past months.......

You can do it both ways:
```php
$mapper->delete($entity);
```
or 
```php
$mapper->delete([$primaryKeyField => $entity->$primaryKeyField]);
```

**Comment by FlipEverything** [comment]
I was writing an example from the top of my head, and I implicitly set the ``$primaryKeyField`` variable. Ofc you can delete an entity if you pass it to ``$mapper->delete``, but you can delete entities if you provide a fitting ``$options`` array as well.

**Comment by FlipEverything** [comment]
Feel free to reopen this thread if you need further assistance.
