### ISSUE TITLE
Relations with conditions, is it possible ?

### ISSUE THREAD

**Issue by Pasichnyk** [spotorm/spot2#257]
Is there a way to put some condition into relations()?

If I have a table: ```"Table 1"```, with fields: ```"user_id", "user_type"```. And I need to connect ```"user_id"``` with table ```"Doctors"``` or with ```"Patients"``` depending on what contains ```"user_type"```.

Thank you.

**Comment by FlipEverything** [comment]
This question isn't Spot related. You can't do that on the relational database level. You can read more about this topic [here](https://stackoverflow.com/a/2003042).

**Comment by Pasichnyk** [comment]
I had guessed it's impossible on the relational database level. But maybe Spot has a way to walk over it?

**Comment by FlipEverything** [comment]
I don't think so. You _can_ define dynamic relations, but you _shouldn't_ really. It would be a mess.

**Comment by Pasichnyk** [comment]
I've understood I need to change structure of the tables. 
But if I would wanted to make that implementation, do I can get value of the field ?

```php
public static function relations(\Spot\MapperInterface  $mapper, \Spot\EntityInterface $entity)
    {
        switch( /* fieldName->value  */ ) //  <- ??
        {
            case "doctor":
                return [
                    "user" => $mapper->belongsTo($entity, "Doctors", "user_id")
                ]
                break;
            case "patient":
                return [
                    "user" => $mapper->belongsTo($entity, "Patients", "user_id")
                ]
                break;
        }
}

```

**Comment by FlipEverything** [comment]
In theory you can do that. You must disable foreign key support and have to implement all the things that will ensure database integrity on the application side (and by default is done by the DBMS).

I don't think that's worth it.
