### ISSUE TITLE
Struggling with belongsTo relationship

### ISSUE THREAD

**Issue by diego-sorribas** [spotorm/spot2#261]
I have this issue and I can not found the error, maybe someone can help me.
I have a Entity called Programs with this relationship
`'pais'       => $mapper->belongsTo($entity, Country::class, 'pais'),`

Then I fetch one program with this line
`  $program = $this->spot->mapper(Program::class)->all()->where(['id' => $programId])->with(['pais'])->first();
`

It triggers this two queries
`SELECT * FROM `programas` WHERE `programas`.`id` = '4' LIMIT 1`
  `SELECT * FROM `paises` WHERE `paises`.`id` IN ('32')`

But when I print $program->pais it return 32 not the object of the relationship, is that okay???

Thanks

**Comment by vlucas** [comment]
All the relations are un-executed query objects that return collections. You can't really print them, but you can loop over them, count them, and execute them.

What happens when you loop over it or count it?

i.e `count($program->pais)` or `foreach($program->pais as $pai) { echo $pai; }`

**Comment by diego-sorribas** [comment]
Is not a collection, it is a 1-N relationship, "pais" is country in english

**Comment by vlucas** [comment]
You are still working with a Relation object though. In this case, `\Spot\Relation\BelongsTo`.

If you want to print the resulting entity, you can use `->entity()` to get it.

i.e. `$program->pais->entity()`

Source: https://github.com/spotorm/spot2/blob/master/lib/Relation/BelongsTo.php#L81

**Comment by FlipEverything** [comment]
Feel free to reopen this thread if you need further assistance.
