### ISSUE TITLE
search query function doesn't work

### ISSUE THREAD

**Issue by cocoon-projet** [spotorm/spot2#266]
When i want to use the search query function. there is an error message.

Error: Call to undefined method Spot\Entity\Manager::datasourceOptions() in D:\wamp\www\SPOTORM\vendor\vlucas\spot2\lib\Query.php on line 445

i looked at the code and i did not see this function.

**Comment by FlipEverything** [comment]
That's a bug: #254 
We'll try to fix that in the future.
