### ISSUE TITLE
Date/Datetime fild.types error

### ISSUE THREAD

**Issue by mateomu18** [spotorm/spot2#267]
When i create an entity with a date/datetime attribute and set de "default" property of this fieldtype like new \Date() or new \DateTime() or new \Date(string) the migration done after returned an error.
Why is this happening?? 
Error:
```
Recoverable fatal error: Object of class DateTime could not be converted to string in /vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php on line 2341
```

My intention is to do something like that:
```
CREATE TABLE table1 (
  date1 datetime NULL DEFAULT now()
);
```
MySql version: 10.2.12-MariaDB
Php version: 7.2.1

Thanks in advance.

**Comment by vlucas** [comment]
The "default" property is for the SQL/db default. Use `value` instead: `'date_created' => ['type' => 'datetime', 'value' => new \DateTime()],`

**Comment by mateomu18** [comment]
Thak you!

2018-06-09 13:34 GMT-03:00 Vance Lucas <notifications@github.com>:
