### ISSUE TITLE
Question about entity validation

### ISSUE THREAD

**Issue by FlipEverything** [spotorm/spot2#272]
Should the entity validation fail silently? Is this by design? For example if I have an entity with required fields like the ```author_id```:

tests/Entity/Post.php
```php
return [
     'author_id' => ['type' => 'integer', 'required' => true],
];
```

And If I do something like in tests/Relations.php
```php
public function testHasManyRelationCountZero()
{
    $mapper = test_spot_mapper('\SpotTest\Entity\Post');
    $post = $mapper->get();
    $post->title = "No Comments";
    $post->body = "<p>Comments relation test</p>";
    $mapper->save($post);

    $this->assertSame(0, count($post->comments));
}
```
The $post->comments will be ```null``` and the ```count($post->comments)``` will throw an error, because the ```$mapper->save($post)``` silently fails with validation error (```author_id is required```). 

Should someone check every ```save()```, ```update()```, etc. operation with ```$entity->hasErrors()``` or ```$result !== false``` or should the validation throw a ```ValidationError``` or something like that?

**Comment by vlucas** [comment]
Yes - this is outlined in the docs here: http://phpdatamapper.com/docs/crud/

**Comment by FlipEverything** [comment]
OK, thank you! I missed that.
