### ISSUE TITLE
fetchAll with IN operator

### ISSUE THREAD

**Issue by dertin** [spotorm/spot2#275]
Hi,

Only one Row is returned for the first Id value but 3 Rows are expected:
```
return $this->connection()->fetchAll('SELECT foo.*
FROM foo
WHERE foo.FooId IN (:FooId)', [':FooId' => '10,23,30']);
```
In the following way, if it works as expected:
```
return $this->connection()->fetchAll('SELECT foo.*
FROM foo
WHERE foo.Id IN (10,23,30)');
```
How should this query be done?

**Comment by FlipEverything** [comment]
You should do the request like this:
```php
return $spot->mapper('foo')->all()->where(['FooId' => [19, 23, 30]]);
```
Raw SQL is not needed in this case.

**Comment by dertin** [comment]
@FlipEverything 

I use Raw SQL in cases where I do not need mapper relationships
I have found that the response is significantly faster.

From what I see, I would not be working with the preparation of the query with the parameters.

**Comment by FlipEverything** [comment]
Ofc it's slower than raw queries, because there are a whole lot happening in the background. I think that you shouldn't use spot if you want to bypass the whole library with raw queries, but I won't argue with you about this topic, feel free to use it as you like.
