### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by amoseev** [spotorm/spot2#277]
Hi! 

I found this project and spot2 came across to me as a good alternative complex Doctrine. But version 2.2.0 was released 2 years ago and project seems abandoned.
Sql Join supports expected since 2016 #175 .

How do you think where the project is moving? Are there any better alternatives?

**Comment by sinuraya** [comment]
Please make this project keep moving. This projects mimics nodejs orm: sequelize. I can easily porting a nodejs project to a php project because of this orm.

**Comment by vlucas** [comment]
Yes, this project is relatively active, but we need to create a new release.

**Comment by FlipEverything** [comment]
Based on the comments above I think you have your answer @amoseev.....
