### ISSUE TITLE
 Example of IS NOT NULL

### ISSUE THREAD

**Issue by dertin** [spotorm/spot2#278]
Hello, how can I include a condition of IS NOT NULL ?
`$mapperTest->all()->where(['Foo <>' => null]);`

**Comment by FlipEverything** [comment]
I think it should work. What does it do? What does ‘->toSql()’ say?

**Comment by FlipEverything** [comment]
I tested it in my own code and 100% positive that it works for me like that:
```php
$this->_mapper->where(['email <>' => NULL]);
```
Feel free to reopen this if you need further assistance (and please provide details). Thank you!
