### ISSUE TITLE
Problem when defining an entity with data of the decimal type

### ISSUE THREAD

**Issue by dertin** [spotorm/spot2#281]
Entity:
`'FichaOrdenPrioridad' => ['type' => 'float', 'length' => [10, 9]]`

MySQL:
`FichaOrdenPrioridad | double NULL`

What I expected in MySQL:
`FichaOrdenPrioridad | decimal(10,9) unsigned NULL`

---
MySQL version: 8.0.11
"vlucas/spot2": "dev-master"

**Comment by FlipEverything** [comment]
Hello!

To achieve what you expected use this:
```php
'FichaOrdenPrioridad' => ['type' => 'decimal', 'precision' => 10, 'scale' => 9, 'unsigned' => true]
```

Result: 
```sql
CREATE TABLE `x` (
  `FichaOrdenPrioridad` decimal(10,9) UNSIGNED DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

If you need further assistance feel free to reopen this issue.
Have a nice day!
