### ISSUE TITLE
Set from Post

### ISSUE THREAD

**Issue by brownrl** [spotorm/spot2#92]
I have about 6 ways to save what a user gives in a _POST form into a spot2 entity. I can't honestly say which one is the best. The issue that I have is that I am usually looping through the fields and then doing a isset check on post and bringing over what was in post... 4 lines of code no biggy but I do it a lot.

I was curious if this could be built into spot2 or if it already is and I don't see it or if you have a handy one liner.

What I would love to do is 

``` PHP
$item->build( $_POST )

// OR

$item->update( $_POST );

// OR 

$item->update( $some_arrayobject );


    // What I currently do, 1 out of 6 different ways that I've played with.
    $data = $item->data();
    foreach ($data as $k => $v) {
        if (isset($_POST[$k])) {
            $item->$k = $_POST[$k];
        }
    }
```

the build almost works but the problem I find is that often I have extra fields or other fields in my $_POST ( saving two separate entities at the same time or ... ) that cause an exception when trying to set or update because that extra field is not in the entity.

Is there way to skip those and just ignore them with build? Oneliner or function that I don't see? 

Regardless I love Spot2 I use it in any project that I can and it has greatly increased the quality of my projects with no more BAD sql statements. Thanks a ton.

**Comment by tuupola** [comment]
Looking at [Spot source](https://github.com/vlucas/spot2/blob/master/lib/Spot/Mapper.php#L803) something like following should work. Did not try this though.

```php
$item->update($_POST, ["strict" => false]);
```

**Comment by brownrl** [comment]
Tried it with

```PHP

$item = $mapper->build( $_POST , [ 'strict' => false ] );
```

Didn't go, also tried $item->update and update is not a entity function.
but I will poke around the library for the strict param. thanks.

**Comment by tuupola** [comment]
```php
$item = $mapper->create( $_POST , [ 'strict' => false ] );
```

**Comment by brownrl** [comment]
nice... thanks a ton. just tried and it went.

This will speed things up. for the other readers, PLEASE make sure to sanitise your data before doing this! Example, maybe the user should not be able to set the ID field. Or maybe you need to convert your checkboxes to 1/0 values for booleans.

**Comment by vlucas** [comment]
I used to do this too out of convenience, but now I *always* manually specify the fields to be updated so that users cannot use tools like the developer console to add fields in, and set things I don't want them to, like changing their `id` or changing the `user_id` column on an entity, etc.

So now I always do something like:
```
$item = $mapper->create([
    'name' => $_POST['name'],
    'description' => $_POST['description'],
    'date_start' => $_POST['date_start'] ? new \DateTime($_POST['date_start']) : null
    // etc...
]);
```

**Comment by brownrl** [comment]
In my projects I made a utility page to generate PHP code for copy and paste. I just tell it the table and it generates base code to handle each field. Then I comment out or delete the ones I don't need and sanitise the rest. pvar() is a function to pre-test isset the _POST var.

```php
  $mapper = $spot->mapper( 'Entity\Subscribers' );
  $item = $mapper->get();

  $item->subscriber_first_name    = pvar( 'subscriber_first_name' );
  $item->subscriber_last_name     = pvar( 'subscriber_last_name' );
  $item->subscriber_email         = pvar( 'subscriber_email' );
  $item->subscriber_created       = time();
  $item->subscriber_title         = pvar( 'subscriber_title' );
  $item->subscriber_language      = LANGUAGE;
  $item->subscriber_street        = pvar( 'subscriber_street' );
  $item->subscriber_number        = pvar( 'subscriber_number' );
  $item->subscriber_city          = pvar( 'subscriber_city' );
  $item->subscriber_zip           = pvar( 'subscriber_zip' );
  $item->subscriber_country       = pvar( 'subscriber_country' );
  $item->subscriber_phone         = pvar( 'subscriber_phone' );
  $item->subscriber_newsletter    = pvar( 'subscriber_newsletter' ) == 'on' ? 1 : 0;
  $item->subscriber_accept        = pvar( 'subscriber_accept' )  == 'on' ? 1 : 0;
  $item->subscriber_brand         = pvar( 'subscriber_brand' );
  
  $mapper->save( $item );
```
