### ISSUE TITLE
how to access Entity in this mapper (Fatal error: Class 'Entity\Post' )

### ISSUE THREAD

**Issue by alishahpakneeds** [spotorm/spot2#93]
Hi I am trying to access Entity but I couldn't able to access

Fatal error: Class 'Entity\Post' not found in /media/d/xampp/htdocs/fakhar/spot3/vendor/vlucas/spot2/lib/Spot/Locator.php on line 51

Please help me in this matter, provide me any guide

Here is my code

require 'vendor/autoload.php';
$cfg = new \Spot\Config();
$cfg->addConnection('mysql', 'mysql://root:admin@localhost/dental2');
$spot = new \Spot\Locator($cfg);
function spot() {
    static $spot;
    if($spot === null) {
        $spot = new \Spot\Locator();
        $spot->config()->addConnection('test_mysql', 'mysql://user:password@localhost/database_name');
    }
    return $spot;
}

$mapper = $spot->mapper('Entity\Post');
$post = $mapper->get(28);

I have created Entity folder and inside folder is my Class Post

Here is my classs
<?php
namespace Entity;

use Spot\EntityInterface as Entity;
use Spot\MapperInterface as Mapper;

class Post extends \Spot\Entity{
    protected static $table = 'oc_product';

```
 public static function fields()
{
    return [
        'product_id'           => ['type' => 'integer', 'primary' => true, 'autoincrement' => true],
        'model'        => ['type' => 'string', 'required' => true],

    ];
}
```

}
?>

**Comment by vlucas** [comment]
Your `Entity\Post` object has to be in the autoload path for Spot to find it.

Ensure you can do this:
```php
$post = new Entity\Post();
```
